name: Release App on Version Tag

on:
  push:
    tags:
      - 'v*' # Only tag releases starting with 'v'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Read release notes
        id: read_release_notes
        run: echo ::set-output name=release_notes::$(cat .dev_logs/release_notes.txt)

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release:
            ${{ steps.read_release_notes.outputs.release_notes }}
          draft: false
          prerelease: false
